import { useAppDispatch, useAppSelector } from '../../../common/hooks/hooks-redux'
import { RootState } from '../../../common/hooks/store-redux'

import { SET_DATADOCUMENT, SET_IS_LOADING } from './store'

export function UseExpiredListController() {
  const state = useAppSelector((state: RootState) => state.dataExpired)
  const dispatch = useAppDispatch()
  const getAllData = () => {
    dispatch(SET_IS_LOADING(true))
    // fetch Api from Server
    const dataToAPi = [
      {
        ngay_ban_hanh: '12/04/2022',
        so_ky_hieu: 2,
        don_vi_vao_so: 'Hội đồng Sáng lập Tập đoàn',
        don_vi_soan_thao: 'Ngân hàng nhà nước Việt Nam',
        loai_van_ban: 'Nghị định',
        trich_yeu: 'Test hiển thị thống kê truy cập',
        ngay_hieu_luc: '12/04/2022',
        tinh_trang_hieu_luc: '12',
        nguoi_ky: 'Thường',
        do_mat: 'Thường',
      },
      {
        ngay_ban_hanh: '12/04/2022',
        so_ky_hieu: 2,
        don_vi_vao_so: 'Hội đồng Sáng lập Tập đoàn',
        don_vi_soan_thao: 'Ngân hàng nhà nước Việt Nam',
        loai_van_ban: 'Nghị định',
        trich_yeu: 'Test hiển thị thống kê truy cập',
        ngay_hieu_luc: '12/04/2022',
        tinh_trang_hieu_luc: '12',
        nguoi_ky: 'Thường',
        do_mat: 'Thường',
      },
      {
        ngay_ban_hanh: '12/04/2022',
        so_ky_hieu: 2,
        don_vi_vao_so: 'Hội đồng Sáng lập Tập đoàn',
        don_vi_soan_thao: 'Ngân hàng nhà nước Việt Nam',
        loai_van_ban: 'Nghị định',
        trich_yeu: 'Test hiển thị thống kê truy cập',
        ngay_hieu_luc: '12/04/2022',
        tinh_trang_hieu_luc: '12',
        nguoi_ky: 'Thường',
        do_mat: 'Thường',
      },
      {
        ngay_ban_hanh: '12/04/2022',
        so_ky_hieu: 2,
        don_vi_vao_so: 'Hội đồng Sáng lập Tập đoàn',
        don_vi_soan_thao: 'Ngân hàng nhà nước Việt Nam',
        loai_van_ban: 'Nghị định',
        trich_yeu: 'Test hiển thị thống kê truy cập',
        ngay_hieu_luc: '12/04/2022',
        tinh_trang_hieu_luc: '12',
        nguoi_ky: 'Thường',
        do_mat: 'Thường',
      },
      {
        ngay_ban_hanh: '12/04/2022',
        so_ky_hieu: 2,
        don_vi_vao_so: 'Hội đồng Sáng lập Tập đoàn',
        don_vi_soan_thao: 'Ngân hàng nhà nước Việt Nam',
        loai_van_ban: 'Nghị định',
        trich_yeu: 'Test hiển thị thống kê truy cập',
        ngay_hieu_luc: '12/04/2022',
        tinh_trang_hieu_luc: '12',
        nguoi_ky: 'Thường',
        do_mat: 'Thường',
      },
      {
        ngay_ban_hanh: '12/04/2022',
        so_ky_hieu: 2,
        don_vi_vao_so: 'Hội đồng Sáng lập Tập đoàn',
        don_vi_soan_thao: 'Ngân hàng nhà nước Việt Nam',
        loai_van_ban: 'Nghị định',
        trich_yeu: 'Test hiển thị thống kê truy cập',
        ngay_hieu_luc: '12/04/2022',
        tinh_trang_hieu_luc: '12',
        nguoi_ky: 'Thường',
        do_mat: 'Thường',
      },
      {
        ngay_ban_hanh: '12/04/2022',
        so_ky_hieu: 2,
        don_vi_vao_so: 'Hội đồng Sáng lập Tập đoàn',
        don_vi_soan_thao: 'Ngân hàng nhà nước Việt Nam',
        loai_van_ban: 'Nghị định',
        trich_yeu: 'Test hiển thị thống kê truy cập',
        ngay_hieu_luc: '12/04/2022',
        tinh_trang_hieu_luc: '12',
        nguoi_ky: 'Thường',
        do_mat: 'Thường',
      },
      {
        ngay_ban_hanh: '12/04/2022',
        so_ky_hieu: 2,
        don_vi_vao_so: 'Hội đồng Sáng lập Tập đoàn',
        don_vi_soan_thao: 'Ngân hàng nhà nước Việt Nam',
        loai_van_ban: 'Nghị định',
        trich_yeu: 'Test hiển thị thống kê truy cập',
        ngay_hieu_luc: '12/04/2022',
        tinh_trang_hieu_luc: '12',
        nguoi_ky: 'Thường',
        do_mat: 'Thường',
      },
      {
        ngay_ban_hanh: '12/04/2022',
        so_ky_hieu: 2,
        don_vi_vao_so: 'Hội đồng Sáng lập Tập đoàn',
        don_vi_soan_thao: 'Ngân hàng nhà nước Việt Nam',
        loai_van_ban: 'Nghị định',
        trich_yeu: 'Test hiển thị thống kê truy cập',
        ngay_hieu_luc: '12/04/2022',
        tinh_trang_hieu_luc: '12',
        nguoi_ky: 'Thường',
        do_mat: 'Thường',
      },
      {
        ngay_ban_hanh: '12/04/2022',
        so_ky_hieu: 2,
        don_vi_vao_so: 'Hội đồng Sáng lập Tập đoàn',
        don_vi_soan_thao: 'Ngân hàng nhà nước Việt Nam',
        loai_van_ban: 'Nghị định',
        trich_yeu: 'Test hiển thị thống kê truy cập',
        ngay_hieu_luc: '12/04/2022',
        tinh_trang_hieu_luc: '12',
        nguoi_ky: 'Thường',
        do_mat: 'Thường',
      },
      {
        ngay_ban_hanh: '12/04/2022',
        so_ky_hieu: 2,
        don_vi_vao_so: 'Hội đồng Sáng lập Tập đoàn',
        don_vi_soan_thao: 'Ngân hàng nhà nước Việt Nam',
        loai_van_ban: 'Nghị định',
        trich_yeu: 'Test hiển thị thống kê truy cập',
        ngay_hieu_luc: '12/04/2022',
        tinh_trang_hieu_luc: '12',
        nguoi_ky: 'Thường',
        do_mat: 'Thường',
      },
      {
        ngay_ban_hanh: '12/04/2022',
        so_ky_hieu: 2,
        don_vi_vao_so: 'Hội đồng Sáng lập Tập đoàn',
        don_vi_soan_thao: 'Ngân hàng nhà nước Việt Nam',
        loai_van_ban: 'Nghị định',
        trich_yeu: 'Test hiển thị thống kê truy cập',
        ngay_hieu_luc: '12/04/2022',
        tinh_trang_hieu_luc: '12',
        nguoi_ky: 'Thường',
        do_mat: 'Thường',
      },
      {
        ngay_ban_hanh: '12/04/2022',
        so_ky_hieu: 2,
        don_vi_vao_so: 'Hội đồng Sáng lập Tập đoàn',
        don_vi_soan_thao: 'Ngân hàng nhà nước Việt Nam',
        loai_van_ban: 'Nghị định',
        trich_yeu: 'Test hiển thị thống kê truy cập',
        ngay_hieu_luc: '12/04/2022',
        tinh_trang_hieu_luc: '12',
        nguoi_ky: 'Thường',
        do_mat: 'Thường',
      },
      {
        ngay_ban_hanh: '12/04/2022',
        so_ky_hieu: 2,
        don_vi_vao_so: 'Hội đồng Sáng lập Tập đoàn',
        don_vi_soan_thao: 'Ngân hàng nhà nước Việt Nam',
        loai_van_ban: 'Nghị định',
        trich_yeu: 'Test hiển thị thống kê truy cập',
        ngay_hieu_luc: '12/04/2022',
        tinh_trang_hieu_luc: '12',
        nguoi_ky: 'Thường',
        do_mat: 'Thường',
      },
      {
        ngay_ban_hanh: '12/04/2022',
        so_ky_hieu: 2,
        don_vi_vao_so: 'Hội đồng Sáng lập Tập đoàn',
        don_vi_soan_thao: 'Ngân hàng nhà nước Việt Nam',
        loai_van_ban: 'Nghị định',
        trich_yeu: 'Test hiển thị thống kê truy cập',
        ngay_hieu_luc: '12/04/2022',
        tinh_trang_hieu_luc: '12',
        nguoi_ky: 'Thường',
        do_mat: 'Thường',
      },
    ]
    // lâý dc data thì lư da ta vào store thông qua action
    dispatch(SET_DATADOCUMENT(dataToAPi))
    ///

    dispatch(SET_IS_LOADING(false))
  }
  return {
    state,
    getAllData,
  }
}
